### PR TITLE
feat: mix outline and canvas content preview

### PR DESCRIPTION
**Pull request by Myriad-Dreamin**
The mixed mode is mainly for previewing slides written in typst.

image

This PR switch render mode of content in sidebar to `RenderMode.Canvas`:
Pros:
+ Improve render quality.
+ Improve performance on scrolling and resizing.

Cons:
+ The elements in canvas is not clickable. (and it is hard to make jump feature as perfect as that in `RenderMode.Svg`)

Then, based on canvas pages, we add a incremental rendered outline.

User action 1:

If an outline item has span information, we can click it and jump to the destination.

image

If an outline item has children, its title element will be styled with underline and clickable. After clicking, fold or unfold the list of children:

User action 2: Case 2.0: If there is only an outline item with biggest level inside of one page, the only item is clickable:

image

Case 2.1: If there are multiple and same-level outline items inside of one page, the last item is clickable, while the rest items is clickable:

image

Case 2.2: Fold state:

image

Case 2.3: Unfold state:

image

---

There are still bugs and features to do but don't bother a lot, leaving for future improvement.
+ [ ] Improvement: Incremental rendering outline doesn't regard state of collapse.
+ [ ] Improvement: Sidebar doesn't update outline items and content at the same time because there is time between two update event.
+ [ ] Feature: Add a button to switch between mixed and non-mixed mode.

### CODE REVIEW

**Comment by Myriad-Dreamin** [comment]
:+1:. I will see all themes on my vscode and garden appearence tomorrow.

**Comment by Myriad-Dreamin** [comment]
It looks better 😆.

The selection color is set to `background-color: var(--vscode-editor-selectionHighlightBackground, #7db9de6c)`.

image

image

image

image

image

**Comment by Enter-tainer** [comment]
cool!

**Comment by Enter-tainer** [comment]
I will release a new version later

**Pull request merged**
