### PR TITLE
fix sensitive scale on touchpad

### LINKED ISSUE #208: Zooming in the preview window is too sensitive using MacBook trackpad
**Describe the bug**
Zooming in the preview window in VSCode using MacBook trackpad is way too sensitive. Even a miniscule pinch gesture can cause huge zoom. Same when zooming out. It is very hard to be precise and the sensitivity is a lot higher than in any other apps. It is now barely usable. I'd make the zoom steps very roughly 80% smaller.

**To Reproduce**
Steps to reproduce the behavior (Library test):
1. Open the preview view.
2. Use 2-finger pinch gesture to zoom in or out.

**Expected behavior**
Zoom should work as expected with the same sensitivity as in other macOS applications.

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0```

typst-preview extension version: `v0.10.2`

**Other info**

MacBook Pro M1 Pro 16"
macOS 14.1.1

### LINKED ISSUE #238: sensitive scrolling
**Describe the bug**
In vscode I've cought extremely sensitive scrolling
**To Reproduce**
Steps to reproduce the behavior (Library test):
1. Declare a rust test 'fn test_xxx() { ... }' or typescript test 'it_should(function () { ... })'
2. Execute test function
3. See error

Or (Shell code):

1. Attach necessary resources to execute shell code
2. Put down some shell code 'cargo run --bin typst-ts-cli -- ...'
3. Execute shell code

**Expected behavior**

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.12-x64v4-xanmod1
```

typst-preview extension version: `v0.7.3`

**Logs:**

typst-preview server log(Output Panel -> typst-preview):
```plain

```

typst-preview client log(Help -> Toggle Developer Tools -> Console):
```plain

```

**Additional context**

### PR DESCRIPTION
**Pull request by Enter-tainer**
fix #238 fix #208

I just randomly choose a threshold, and currently I don't have a mouse. Please test!

### CODE REVIEW

**Comment by Myriad-Dreamin** [comment]
Please check https://github.com/mozilla/pdf.js/blob/master/web/app.js#L2616-L2618. The magic numbers are really magic and they affect user experience. We may not seek a homemade "pinch-to-zoom" but just follow what pdf.js does.

**Comment by Enter-tainer** [comment]
these code looks far more complicate than current ones. it includes checks for different hardware(touchpad, ctrl+wheel) and different delta mode(line, pixel, page). do you mean we should do similar thing? i think it is too complex for now

**Comment by Myriad-Dreamin** [comment]
> these code looks far more complicate than current ones. it includes checks for different hardware(touchpad, ctrl+wheel) and different delta mode(line, pixel, page). do you mean we should do similar thing? i think it is too complex for now

The current ctrl+wheel handling was simplified from that in pdf.js. Following what it does, we didn't accumulate `deltaDistance` in line mode (when using mouse). However, this PR would like to accumulate `deltaDistance` for any devices (when using mouse, touchpad etc.).

Though pdf.js implements a complicated wheel handler, I think we need to understand that handler before making any changes.

**Comment by Enter-tainer** [comment]
does mouse use line mode? i dont have a mouse at this moment

**Comment by Enter-tainer** [comment]
for now i think we can simply divide the problem into 2 parts. for pixel ones, we accumulate scroll distance and only trigger 1 scale event. for line ones, we can reuse the original logic

**Comment by Myriad-Dreamin** [comment]
> does mouse use line mode? i dont have a mouse at this moment

I don't have one either. :crying_cat_face: :smile_cat:

**Comment by Myriad-Dreamin** [comment]
> for now i think we can simply divide the problem into 2 parts. for pixel ones, we accumulate scroll distance and only trigger 1 scale event. for line ones, we can reuse the original logic

there are two parts in the wheel handler of pdf.js. the first one is for smooth zooming with a touchpad like device, and we are on the second part. We may just replicate the second part for simplicity.

**Comment by Enter-tainer** [comment]
I just test this with my mouse and it works the same as before

**Pull request merged**
